### ISSUE TITLE
ImportError: cannot import name nefis

### ISSUE THREAD

**Issue by besty1993** [ymzkala/nefis-cython#1]
Hello,

I downloaded nefis.dll and nefis.pyd and put them in the source code directory
And then, I installed it by typing
```
pip install -e .
```
But I have an error while I import it.
The error says, 

```
>>> import nefiscython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nefiscython\__init__.py", line 1, in <module>
    from .nefismain import *
  File "nefiscython\nefismain.py", line 8, in <module>
    from lib import nefis
ImportError: cannot import name nefis
```

How can I fix this?

Thanks in advance

**Comment by besty1993** [comment]
I solved this somehow:
realized that nefis.pyd itself can be imported, I placed nefismain.py and nefis.pyd in the same place and imported nefismain.py in the python code I want to use nefis.

I should've studied Cython first before using this module

Thanks
